codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down

  status:
    project: false
    patch: false

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

flag_management:
  individual_flags:
    - name: provider_kit
      paths:
        - packages/provider_kit/**
      carryforward: false
      statuses:
        - type: project
          target: 100%
          threshold: 0%
        - type: patch
          target: 100%
          threshold: 0%

    - name: rate_kit
      paths:
        - packages/rate_kit/**
      carryforward: false
      statuses:
        - type: project
          target: 100%
          threshold: 0%
        - type: patch
          target: 100%
          threshold: 0%