name: provider_kit
description: "A tool kit for provider package with predefined builders, listeners, caches, observers and much more with reduced boilerplate."
version: 0.0.1
repository: https://github.com/RAMb002/provider_kit
issue_tracker: https://github.com/RAMb002/provider_kit/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

